name: smartcropx
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.18.1
  url_launcher: ^6.2.4
  webview_flutter: ^4.4.2
  supabase_flutter: ^2.5.3
  provider: ^6.1.1
  flutter_dotenv: ^5.1.0
  uuid: ^4.2.1
  qr_flutter: ^4.1.0
  lottie: ^2.7.0
  flutter_slidable: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

# Launcher icon configuration
flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/bg.jpg
    - assets/logo.png
    - .env